name: "Submodules Sync | 同步子模块"

on:
  schedule:
    - cron: "0 6,18 * * *"
  workflow_dispatch:
jobs:
  submodules-sync:
    name: "Submodules Sync | 同步子模块"
    runs-on: ubuntu-latest
    if: github.repository == 'misitebao/blog'
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout | 切换到部署分支
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Git | 设置Git
        run: |
          git config --local user.email "i@misitebao.com"
          git config --local user.name "Misite Bao"

      - name: Git Sumbodule Update | 更新子模块
        run: |
          git submodule update --progress --init --recursive --force --remote -- "content"

      - name: Automatic submission | 自动提交
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          commit_prefix: ""
          commit_message: "feat: update content submodules"
